### ISSUE TITLE
add anonymize parameter to has_ipv4() function 

### ISSUE THREAD

**Issue by larrykimutai** [NCATComp410/comp410_spring_2022#160]

**Comment by claesmk** [comment]
As mentioned in the original assignment, in sprint-4 a csv file will be provided which will need to be anonymized.  Here is an example of some of the content:

"Customer Sue Martin contacted the help desk to report an issue with their IPv4 address 192.168.185.88"

So you will need to make sure you can handle an IPv4 address that is in the middle of a string of text.
