### ISSUE TITLE
Adding Aggie Slogan

### ISSUE THREAD

**Issue by DAndreBrown** [NCATComp410/comp410_spring_2022#55]

**Comment by DAndreBrown** [comment]
Will add "aggies do" as my slogan.

**Comment by DAndreBrown** [comment]
New slogan is "Move forward with purpose."

**Comment by claesmk** [comment]
@DAndreBrown let me know if you need some help with your pull request

**Comment by DAndreBrown** [comment]
Good morning,

Yes, I was planning to reach out on Monday, but if you can help today then
all the better. I was following the zoom recording and I got to the part
where I had to push and it wouldn't let me. The error kept saying check the
output window, but the output window tells me nothing new either. I made my
email public on my github account but that did not fix the issue either.
Any help is appreciated.


Thanks,

D'Andre Brown

**Comment by claesmk** [comment]
Would you be available later tonight (Monday 7th)?  Maybe after 7pm?

**Comment by DAndreBrown** [comment]
I have to be somewhere at 7 but I could do 7:30 yo 9 at the latest.

**Comment by claesmk** [comment]
Let's try 7:30

Monday, Feb 7 · 7:30–8 PM
Google Meet joining info
Video call [link](https://meet.google.com/dwn-njpx-xpm)
