### ISSUE TITLE
Specification of IPV6

### ISSUE THREAD

**Issue by TangBaiFeng** [NCATComp410/comp410_spring_2022#71]
Below is an except about valid IPV6 addresses from IBM. Will we be handling all cases, or run under the assumption that it will be 8 series of 4 hexadecimal with a colon in-between (the first 2 examples under normal). Ignore the emoji, github markdown

> The following are examples of valid IPv6 (normal) addresses:
> 
> - 2001:db8:3333:4444:5555:6666:7777:8888
> - 2001:db8:3333:4444:CCCC:DDDD:EEEE:FFFF
> - :: (implies all 8 segments are zero)
> - 2001:db8:: (implies that the last six segments are zero)
> - ::1234:5678 (implies that the first six segments are zero)
> - 2001:db8::1234:5678 (implies that the middle four segments are zero)
> - 2001:0db8:0001:0000:0000:0ab9:C0A8:0102 (This can be compressed to eliminate leading zeros, as follows: 2001:db8:1::ab9:C0A8:102 )
> 
> The following are examples of valid IPv6 (dual) addresses:
> 
> - 2001:db8:3333:4444:5555:6666:1.2.3.4
> - ::11.22.33.44 (implies all six IPv6 segments are zero)
> - 2001:db8::123.123.123.123 (implies that the last four IPv6 segments are zero)
> - ::1234:5678:91.123.4.56 (implies that the first four IPv6 segments are zero)
> - ::1234:5678:1.2.3.4 (implies that the first four IPv6 segments are zero)
> - 2001:db8::1234:5678:5.6.7.8 (implies that the middle two IPv6 segments are zero)

**Comment by claesmk** [comment]
Since we'll only be removing potential PII there is no need to detect valid/invalid IPv6 addresses.  You can assume that it will be 8 series of 4 hexadecimal with a colon in-between
