### ISSUE TITLE
Implement has() function for name

### ISSUE THREAD

**Issue by setisdale** [NCATComp410/comp410_spring_2022#81]

**Comment by claesmk** [comment]
Names can be a difficult thing to detect without implementing a name detection API.  For this requirement you can assume a name is something like John Smith - which would be two words right next to each other that are capitalized.  You should not match something like Seattle, Washington, however you might match something like 123 Brown Street, which I will accept. However, feel free to implement the code to avoid matching something like 123 Brown Street if you'd like or leave it as a TODO.

**Comment by setisdale** [comment]
So just to double check, if someone entered "Seattle Washington" that would work but not "Seattle, Washington. That's only because we're making this exception for requirements of the name

**Comment by setisdale** [comment]
Also, I made it where 123 Brown Street wouldn't be accepted since names don't have numbers
